version: 0.3.{build}
skip_tags: true
image:
  - Visual Studio 2017
init:
- ps:
environment:
  PowershellGalleryKey:
    secure: pRPJORXDzl7G6sU5Qz+K+tvDpzwYY+KgXDzAkY31Zb6cxKUJFFzYvzci7+Xgt0xN
  GitHubKey:
    secure: 64LLgggYJc3bb1D7G22KGYQFHknuWvoFZAUewRfX0QXV8gBjG97WwwU9lC2HNQ99
install:
- ps: |
    import-module powershellget
    Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck
    Remove-Module PowerShellGet -Force
    Import-Module PowerShellGet -Force

    Get-PackageProvider -Name NuGet -ForceBootstrap

    install-module pester -force -AllowClobber -SkipPublisherCheck
    install-module PSScriptAnalyzer -force -AllowClobber -SkipPublisherCheck
build_script:
- ps: |
      if($env:APPVEYOR_REPO_BRANCH -ne "master" -or $env:APPVEYOR_PULL_REQUEST_NUMBER -or $env:APPVEYOR_REPO_COMMIT_MESSAGE -like "skip: *" -or $env:OS -ne "Windows_NT") {
        .\Invoke-Build.ps1 build,test
      } else {
        .\Invoke-Build.ps1 publish
      }

artifacts:
  - path: AnsibleTower.zip

deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: 64LLgggYJc3bb1D7G22KGYQFHknuWvoFZAUewRfX0QXV8gBjG97WwwU9lC2HNQ99
  draft: true
  on:
    APPVEYOR_REPO_BRANCH: master
    OS: Windows_NT
