version: 0.3.{build}
skip_tags: true
image:
  - ubuntu1804
  - Visual Studio 2017
init:
- ps:
- sh: export PATH=/home/appveyor/.local/bin:$PATH
environment:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  PowershellGalleryKey:
    secure: pRPJORXDzl7G6sU5Qz+K+tvDpzwYY+KgXDzAkY31Zb6cxKUJFFzYvzci7+Xgt0xN
  GitHubKey:
    secure: 64LLgggYJc3bb1D7G22KGYQFHknuWvoFZAUewRfX0QXV8gBjG97WwwU9lC2HNQ99
install:
- ps: |
    import-module powershellget
    Install-module PowerShellGet -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
    Remove-Module PowerShellGet -Force
    Import-Module PowerShellGet -Force

    Get-PackageProvider -Name NuGet -ForceBootstrap

    install-module pester -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
    install-module PSScriptAnalyzer -force -AllowClobber -SkipPublisherCheck -Scope CurrentUser
- sh: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
- sh: sudo chmod +x /usr/local/bin/docker-compose
- sh: pip install --user ansible-tower-cli
test_script:
- ps: |
      if($env:OS -ne "Windows_NT") {
        .\Invoke-Build.ps1 IntegrationTests
      }
build_script:
- ps: |
      if( $env:APPVEYOR_REPO_BRANCH -eq "master" -and !$env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_REPO_COMMIT_MESSAGE -notlike "skip: *" -and $env:OS -eq "Windows_NT" ) {
        .\Invoke-Build.ps1 publish
      } else {
        .\Invoke-Build.ps1 build,test
      }

artifacts:
  - path: AnsibleTower.zip

deploy:
- provider: GitHub
  tag: $(APPVEYOR_BUILD_VERSION)
  auth_token:
    secure: 64LLgggYJc3bb1D7G22KGYQFHknuWvoFZAUewRfX0QXV8gBjG97WwwU9lC2HNQ99
  draft: true
  on:
    APPVEYOR_REPO_BRANCH: master
    OS: Windows_NT
